DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS consent_requests CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS consents CASCADE;
DROP TABLE IF EXISTS health_records CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;
DROP TABLE IF EXISTS diseases CASCADE;

ALTER TABLE IF EXISTS facilities DROP CONSTRAINT IF EXISTS fk_facilities_facility_admin;
ALTER TABLE IF EXISTS woredas DROP CONSTRAINT IF EXISTS fk_woredas_woreda_admin;
ALTER TABLE IF EXISTS zones DROP CONSTRAINT IF EXISTS fk_zones_zonal_admin;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS facilities CASCADE;
DROP TABLE IF EXISTS woredas CASCADE;
DROP TABLE IF EXISTS zones CASCADE;

DROP TYPE IF EXISTS consent_request_status;
DROP TYPE IF EXISTS consent_status;
DROP TYPE IF EXISTS user_role;
