DROP POLICY IF EXISTS patients_select ON patients;
DROP POLICY IF EXISTS patients_insert ON patients;
DROP POLICY IF EXISTS patients_update_patient ON patients;

DROP POLICY IF EXISTS health_records_select ON health_records;
DROP POLICY IF EXISTS health_records_insert ON health_records;
DROP POLICY IF EXISTS health_records_update ON health_records;

DROP POLICY IF EXISTS consents_select ON consents;
DROP POLICY IF EXISTS consents_insert ON consents;
DROP POLICY IF EXISTS consents_update ON consents;

DROP POLICY IF EXISTS consent_requests_all ON consent_requests;

DROP POLICY IF EXISTS appointments_select ON appointments;
DROP POLICY IF EXISTS appointments_mutate ON appointments;

DROP POLICY IF EXISTS audit_logs_select ON audit_logs;
DROP POLICY IF EXISTS audit_logs_insert ON audit_logs;

DROP POLICY IF EXISTS diseases_read ON diseases;
DROP POLICY IF EXISTS medicines_read ON medicines;
DROP POLICY IF EXISTS zones_read ON zones;
DROP POLICY IF EXISTS woredas_read ON woredas;
DROP POLICY IF EXISTS facilities_read ON facilities;

ALTER TABLE IF EXISTS patients NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS health_records NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consent_requests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS appointments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS diseases NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS medicines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS zones NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS woredas NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS facilities NO FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS health_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consent_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS diseases DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS medicines DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS zones DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS woredas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS facilities DISABLE ROW LEVEL SECURITY;

DROP FUNCTION IF EXISTS medilink.session_user_id();
DROP FUNCTION IF EXISTS medilink.session_role();

DROP SCHEMA IF EXISTS medilink;
