-- Ensure minimum catalog sizes required by MediLink:
-- 30 diseases and 20 medicines with bilingual labels.
-- Safe to re-run due to ON CONFLICT (slug) DO NOTHING.

INSERT INTO diseases (
  slug, name, name_am, category, description, description_am,
  symptoms, symptoms_am, causes, causes_am, prevention, prevention_am,
  treatment, treatment_am, severity, body_regions, seasonal, seasonal_am, prevalence
)
VALUES
  ('malaria', 'Malaria', 'ወባ', 'infectious', 'Mosquito-borne infectious disease.', 'በትንኝ የሚተላለፍ በሽታ ነው።',
   ARRAY['Fever','Chills'], ARRAY['ትኩሳት','ብርድ ብርድ'],
   ARRAY['Mosquito bites'], ARRAY['የትንኝ ንክሻ'],
   ARRAY['Use mosquito nets'], ARRAY['የትንኝ መረብ መጠቀም'],
   ARRAY['Antimalarial treatment'], ARRAY['ፀረ-ወባ ሕክምና'],
   'severe', ARRAY['blood','liver'], ARRAY['rainy season'], ARRAY['ዝናባማ ወቅት'], '{"region":"Jimma Zone","prevalence":"high"}'::jsonb),
  ('asthma', 'Asthma', 'አስም', 'chronic', 'Chronic airway inflammation causing breathing difficulty.', 'በረጅም ጊዜ የመተንፈሻ እብጠት የሚያመጣ በሽታ ነው።',
   ARRAY['Wheezing','Shortness of breath'], ARRAY['ማስነጠስ','የትንፋሽ ማጠር'],
   ARRAY['Allergens','Smoke'], ARRAY['አለርጂ','ጭስ'],
   ARRAY['Avoid triggers'], ARRAY['ቀስቅሴዎችን መቆጠብ'],
   ARRAY['Inhalers'], ARRAY['ኢንሄለር'],
   'moderate', ARRAY['lungs','chest'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('hiv-aids', 'HIV/AIDS', 'ኤችአይቪ/ኤድስ', 'chronic', 'Viral condition affecting immunity.', 'የበሽታ መከላከያን የሚጎዳ ቫይረስ ነው።',
   ARRAY['Weight loss','Fatigue'], ARRAY['ክብደት መቀነስ','ድካም'],
   ARRAY['Unprotected sex'], ARRAY['ጥበቃ የሌለው ወሲብ'],
   ARRAY['Testing','Condom use'], ARRAY['ምርመራ','ኮንዶም መጠቀም'],
   ARRAY['ART therapy'], ARRAY['ART ሕክምና'],
   'critical', ARRAY['immune system'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('rheumatoid-arthritis', 'Rheumatoid Arthritis', 'ሩማቶይድ አርትራይተስ', 'autoimmune', 'Autoimmune inflammatory joint disease.', 'የመገጣጠሚያ ራስን-በራስ እብጠት በሽታ ነው።',
   ARRAY['Joint pain','Morning stiffness'], ARRAY['የመገጣጠሚያ ህመም','የጠዋት መደንዘዝ'],
   ARRAY['Immune dysregulation'], ARRAY['የኢሚዩን መዛባት'],
   ARRAY['Early diagnosis'], ARRAY['ቀደምት ምርመራ'],
   ARRAY['DMARDs'], ARRAY['DMARDs መድሀኒት'],
   'moderate', ARRAY['joints','hands'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('type1-diabetes', 'Type 1 Diabetes', 'ዓይነት 1 የስኳር በሽታ', 'autoimmune', 'Insulin deficiency due to autoimmune destruction.', 'በራስን-በራስ ጥቃት ምክንያት የኢንሱሊን እጥረት።',
   ARRAY['Frequent urination','Thirst'], ARRAY['ተደጋጋሚ ሽንት','ጥማት'],
   ARRAY['Autoimmune causes'], ARRAY['ራስን-በራስ ምክንያቶች'],
   ARRAY['Monitoring'], ARRAY['መከታተል'],
   ARRAY['Insulin therapy'], ARRAY['የኢንሱሊን ሕክምና'],
   'severe', ARRAY['pancreas'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('chronic-kidney-disease', 'Chronic Kidney Disease', 'የኩላሊት ዘላቂ በሽታ', 'silent', 'Progressive kidney function decline.', 'የኩላሊት ስራ ቀስ በቀስ መቀነስ።',
   ARRAY['Swelling','Fatigue'], ARRAY['እብጠት','ድካም'],
   ARRAY['Diabetes','Hypertension'], ARRAY['ስኳር በሽታ','የደም ግፊት'],
   ARRAY['Regular screening'], ARRAY['መደበኛ ምርመራ'],
   ARRAY['Diet and medication'], ARRAY['አመጋገብ እና መድሀኒት'],
   'severe', ARRAY['kidneys'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('hepatitis-b-c', 'Hepatitis B and C', 'ሄፐታይቲስ B እና C', 'silent', 'Viral liver infections.', 'የጉበት ቫይረስ ኢንፌክሽኖች።',
   ARRAY['Jaundice','Fatigue'], ARRAY['መቢጫ መሆን','ድካም'],
   ARRAY['Blood exposure'], ARRAY['የደም መጋለጥ'],
   ARRAY['Vaccination'], ARRAY['ክትባት'],
   ARRAY['Antiviral care'], ARRAY['ፀረ-ቫይረስ ሕክምና'],
   'severe', ARRAY['liver'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('high-cholesterol', 'High Cholesterol', 'ከፍተኛ ኮሌስትሮል', 'silent', 'Elevated blood lipids increasing heart risk.', 'የደም ስብ መጨመር የልብ አደጋን ያሳድጋል።',
   ARRAY['Often no symptoms'], ARRAY['ብዙ ጊዜ ምልክት የለም'],
   ARRAY['Diet','Genetics'], ARRAY['አመጋገብ','የዘር ውርስ'],
   ARRAY['Healthy diet'], ARRAY['ጤናማ አመጋገብ'],
   ARRAY['Statins'], ARRAY['ስታቲን መድሀኒት'],
   'moderate', ARRAY['heart','blood vessels'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('sleep-apnea', 'Sleep Apnea', 'የእንቅልፍ መቆራረጥ', 'silent', 'Repeated breathing interruptions during sleep.', 'በእንቅልፍ ጊዜ የሚደጋገም የትንፋሽ ቆራጭ ችግር።',
   ARRAY['Snoring','Daytime sleepiness'], ARRAY['ማስነጠስ','በቀን እንቅልፍ'],
   ARRAY['Obesity'], ARRAY['ክብደት መጨመር'],
   ARRAY['Weight management'], ARRAY['ክብደት መቆጣጠር'],
   ARRAY['CPAP'], ARRAY['CPAP ሕክምና'],
   'moderate', ARRAY['airway','lungs'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('glaucoma', 'Glaucoma', 'ግላኮማ', 'silent', 'Optic nerve damage causing progressive vision loss.', 'የዓይን ነርቭ ጉዳት በቀስታ የእይታ መጥፋትን ያመጣል።',
   ARRAY['Vision loss'], ARRAY['የእይታ መቀነስ'],
   ARRAY['High eye pressure'], ARRAY['ከፍተኛ የዓይን ግፊት'],
   ARRAY['Eye screening'], ARRAY['የዓይን ምርመራ'],
   ARRAY['Eye drops'], ARRAY['የዓይን ነጠብጣብ'],
   'severe', ARRAY['eyes'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('hypothyroidism', 'Hypothyroidism', 'የታይሮይድ እጥረት', 'silent', 'Low thyroid hormone function.', 'ዝቅተኛ የታይሮይድ ሆርሞን ስራ።',
   ARRAY['Fatigue','Weight gain'], ARRAY['ድካም','ክብደት መጨመር'],
   ARRAY['Autoimmune causes'], ARRAY['ራስን-በራስ ምክንያቶች'],
   ARRAY['Iodine adequacy'], ARRAY['በቂ አዮዲን'],
   ARRAY['Hormone replacement'], ARRAY['ሆርሞን መተካት'],
   'moderate', ARRAY['thyroid','neck'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('fatty-liver', 'Fatty Liver Disease', 'የጉበት ስብ መከማቸት', 'silent', 'Excess fat deposition in liver.', 'በጉበት ውስጥ ስብ መከማቸት።',
   ARRAY['Often asymptomatic'], ARRAY['ብዙ ጊዜ ምልክት የለም'],
   ARRAY['Obesity','Diabetes'], ARRAY['ክብደት መጨመር','ስኳር በሽታ'],
   ARRAY['Exercise'], ARRAY['እንቅስቃሴ'],
   ARRAY['Weight loss'], ARRAY['ክብደት መቀነስ'],
   'moderate', ARRAY['liver'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('epilepsy', 'Epilepsy', 'ኤፒሌፕሲ', 'chronic', 'Neurological disorder with recurrent seizures.', 'ተደጋጋሚ መንቀጥቀጥ የሚያመጣ የነርቭ ችግር።',
   ARRAY['Seizures'], ARRAY['መንቀጥቀጥ'],
   ARRAY['Neurological causes'], ARRAY['የነርቭ ምክንያቶች'],
   ARRAY['Medication adherence'], ARRAY['መድሀኒት መከተል'],
   ARRAY['Anti-seizure medicines'], ARRAY['ፀረ-መንቀጥቀጥ መድሀኒት'],
   'severe', ARRAY['brain'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('heart-failure', 'Heart Failure', 'የልብ ድካም', 'chronic', 'Heart pumping function is reduced.', 'የልብ የደም ማፍሰስ ስራ ይቀንሳል።',
   ARRAY['Shortness of breath','Swelling'], ARRAY['የትንፋሽ ማጠር','እብጠት'],
   ARRAY['Hypertension'], ARRAY['የደም ግፊት'],
   ARRAY['Control BP'], ARRAY['የደም ግፊት መቆጣጠር'],
   ARRAY['Cardiac medication'], ARRAY['የልብ መድሀኒት'],
   'critical', ARRAY['heart'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('copd', 'COPD', 'ሲኦፒዲ', 'chronic', 'Long-term obstructive lung disease.', 'የረዥም ጊዜ የሳንባ መከልከል በሽታ።',
   ARRAY['Chronic cough'], ARRAY['ዘላቂ ሳል'],
   ARRAY['Smoking'], ARRAY['ማጨስ'],
   ARRAY['Stop smoking'], ARRAY['ማጨስ መቆም'],
   ARRAY['Inhalers'], ARRAY['ኢንሄለር'],
   'severe', ARRAY['lungs'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('sickle-cell', 'Sickle Cell Disease', 'ሲክል ሴል በሽታ', 'chronic', 'Inherited blood disorder causing pain crises.', 'የዘር የደም ችግር ህመም ግጭት ያመጣል።',
   ARRAY['Pain crisis','Anemia'], ARRAY['የህመም ግጭት','የደም ማነስ'],
   ARRAY['Inherited genetics'], ARRAY['የተወረሰ ዘር'],
   ARRAY['Genetic counseling'], ARRAY['የዘር ምክር'],
   ARRAY['Pain management'], ARRAY['ህመም አያያዝ'],
   'severe', ARRAY['blood'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('tuberculosis', 'Tuberculosis', 'ነቀርሳ', 'chronic', 'Bacterial disease affecting lungs.', 'ሳንባን የሚጎዳ ባክቴሪያዊ በሽታ።',
   ARRAY['Persistent cough','Fever'], ARRAY['ዘላቂ ሳል','ትኩሳት'],
   ARRAY['TB bacteria'], ARRAY['የTB ባክቴሪያ'],
   ARRAY['Ventilation','Early treatment'], ARRAY['አየር መንቀሳቀስ','ቀደም ብሎ ሕክምና'],
   ARRAY['Antibiotics'], ARRAY['አንቲባዮቲክ'],
   'severe', ARRAY['lungs'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"high"}'::jsonb),
  ('typhoid-fever', 'Typhoid Fever', 'ታይፎይድ ትኩሳት', 'chronic', 'Food or water-borne bacterial infection.', 'በምግብ ወይም በውሃ የሚተላለፍ ባክቴሪያ በሽታ።',
   ARRAY['High fever','Abdominal pain'], ARRAY['ከፍተኛ ትኩሳት','የሆድ ህመም'],
   ARRAY['Contaminated water'], ARRAY['የተበከለ ውሃ'],
   ARRAY['Safe water'], ARRAY['ንጹህ ውሃ'],
   ARRAY['Antibiotics'], ARRAY['አንቲባዮቲክ'],
   'severe', ARRAY['abdomen'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('lupus', 'Lupus', 'ሉፐስ', 'autoimmune', 'Autoimmune disease affecting multiple organs.', 'ብዙ አካላትን የሚጎዳ ራስን-በራስ በሽታ።',
   ARRAY['Joint pain','Rash'], ARRAY['የመገጣጠሚያ ህመም','ቁርጠት'],
   ARRAY['Immune dysregulation'], ARRAY['የኢሚዩን መዛባት'],
   ARRAY['Regular follow-up'], ARRAY['መደበኛ ክትትል'],
   ARRAY['Immunosuppressants'], ARRAY['ኢሚዩን መቀነሻ መድሀኒት'],
   'severe', ARRAY['skin','joints'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('multiple-sclerosis', 'Multiple Sclerosis', 'ሙልቲፕል ስክሌሮሲስ', 'autoimmune', 'Immune-mediated disease of brain and spine.', 'አእምሮና አከርካሪ ላይ የሚታይ የኢሚዩን በሽታ።',
   ARRAY['Weakness','Numbness'], ARRAY['ድካም','ድንዛዝ'],
   ARRAY['Immune attack'], ARRAY['የኢሚዩን ጥቃት'],
   ARRAY['Early care'], ARRAY['ቀደምት እንክብካቤ'],
   ARRAY['DMT therapy'], ARRAY['DMT ሕክምና'],
   'severe', ARRAY['brain','spine'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('psoriasis', 'Psoriasis', 'ፖሲያሪያሲስ', 'autoimmune', 'Chronic inflammatory skin condition.', 'ዘላቂ የቆዳ እብጠት በሽታ።',
   ARRAY['Scaly patches'], ARRAY['ቅብ ያለ ቆዳ'],
   ARRAY['Immune factors'], ARRAY['የኢሚዩን ምክንያቶች'],
   ARRAY['Skin care'], ARRAY['የቆዳ እንክብካቤ'],
   ARRAY['Topical therapy'], ARRAY['የቆዳ መድሀኒት'],
   'moderate', ARRAY['skin'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('hashimoto', 'Hashimoto Disease', 'ሃሺሞቶ በሽታ', 'autoimmune', 'Autoimmune thyroid inflammation.', 'የታይሮይድ ራስን-በራስ እብጠት።',
   ARRAY['Fatigue'], ARRAY['ድካም'],
   ARRAY['Autoimmune causes'], ARRAY['ራስን-በራስ ምክንያት'],
   ARRAY['Thyroid checks'], ARRAY['የታይሮይድ ምርመራ'],
   ARRAY['Hormone replacement'], ARRAY['ሆርሞን መተካት'],
   'moderate', ARRAY['thyroid'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('graves-disease', 'Graves Disease', 'ግሬቭስ በሽታ', 'autoimmune', 'Autoimmune hyperthyroidism condition.', 'የታይሮይድ ሆርሞን መጨመር የሚያመጣ በሽታ።',
   ARRAY['Fast heartbeat'], ARRAY['ፈጣን የልብ ምት'],
   ARRAY['Autoimmune causes'], ARRAY['ራስን-በራስ ምክንያቶች'],
   ARRAY['Monitoring'], ARRAY['መከታተል'],
   ARRAY['Antithyroid medication'], ARRAY['ፀረ-ታይሮይድ መድሀኒት'],
   'severe', ARRAY['thyroid','heart'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('celiac-disease', 'Celiac Disease', 'ሴሊያክ በሽታ', 'autoimmune', 'Gluten-triggered autoimmune intestinal disease.', 'በግሉተን የሚቀሰቀስ የአንጀት በሽታ።',
   ARRAY['Diarrhea','Bloating'], ARRAY['ተቅማጥ','እብጠት'],
   ARRAY['Gluten sensitivity'], ARRAY['የግሉተን ተጋላጭነት'],
   ARRAY['Gluten-free diet'], ARRAY['ከግሉተን ነፃ አመጋገብ'],
   ARRAY['Dietary management'], ARRAY['የአመጋገብ አያያዝ'],
   'moderate', ARRAY['intestines'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('sjogren-syndrome', 'Sjogren Syndrome', 'ሾግረን ሲንድሮም', 'autoimmune', 'Autoimmune dryness syndrome affecting eyes and mouth.', 'ዓይንና አፍ ደረቅ የሚያደርግ በሽታ።',
   ARRAY['Dry eyes','Dry mouth'], ARRAY['ደረቅ ዓይን','ደረቅ አፍ'],
   ARRAY['Autoimmune causes'], ARRAY['ራስን-በራስ ምክንያቶች'],
   ARRAY['Hydration'], ARRAY['ፈሳሽ መጠጣት'],
   ARRAY['Symptom relief'], ARRAY['ምልክት ማስታገሻ'],
   'moderate', ARRAY['eyes','mouth'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('ibd', 'Inflammatory Bowel Disease', 'የአንጀት እብጠት', 'autoimmune', 'Chronic inflammatory digestive disease.', 'የመፍጫ አካል ዘላቂ እብጠት በሽታ።',
   ARRAY['Abdominal pain','Diarrhea'], ARRAY['የሆድ ህመም','ተቅማጥ'],
   ARRAY['Immune causes'], ARRAY['የኢሚዩን ምክንያቶች'],
   ARRAY['Regular care'], ARRAY['መደበኛ እንክብካቤ'],
   ARRAY['Anti-inflammatory meds'], ARRAY['ፀረ-እብጠት መድሀኒት'],
   'severe', ARRAY['intestines'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('addisons-disease', 'Addisons Disease', 'አዲሰን በሽታ', 'autoimmune', 'Adrenal insufficiency disorder.', 'የአድሬናል ሆርሞን እጥረት በሽታ።',
   ARRAY['Fatigue','Low BP'], ARRAY['ድካም','ዝቅተኛ የደም ግፊት'],
   ARRAY['Autoimmune causes'], ARRAY['ራስን-በራስ ምክንያቶች'],
   ARRAY['Early diagnosis'], ARRAY['ቀደምት ምርመራ'],
   ARRAY['Hormone replacement'], ARRAY['ሆርሞን መተካት'],
   'critical', ARRAY['adrenal','whole body'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('pneumonia', 'Pneumonia', 'የሳንባ ምች', 'infectious', 'Lung infection causing inflammation and breathing problems.', 'በሳንባ ውስጥ ኢንፌክሽን የሚያመጣ በሽታ።',
   ARRAY['Cough','Fever','Chest pain'], ARRAY['ሳል','ትኩሳት','የደረት ህመም'],
   ARRAY['Bacterial/viral infection'], ARRAY['ባክቴሪያ/ቫይረስ ኢንፌክሽን'],
   ARRAY['Vaccination','Hand hygiene'], ARRAY['ክትባት','እጅ ንፅህና'],
   ARRAY['Antibiotics and supportive care'], ARRAY['አንቲባዮቲክ እና ድጋፍ ሕክምና'],
   'severe', ARRAY['lungs'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('measles', 'Measles', 'ኩፍኝ', 'infectious', 'Highly contagious viral disease.', 'በጣም ተላላፊ ቫይረስ በሽታ።',
   ARRAY['Fever','Rash'], ARRAY['ትኩሳት','ቁርጠት'],
   ARRAY['Measles virus'], ARRAY['የኩፍኝ ቫይረስ'],
   ARRAY['Vaccination'], ARRAY['ክትባት'],
   ARRAY['Supportive care'], ARRAY['ድጋፍ ሕክምና'],
   'severe', ARRAY['whole body'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb),
  ('cholera', 'Cholera', 'ኮሌራ', 'infectious', 'Acute diarrheal disease caused by contaminated water.', 'በተበከለ ውሃ የሚመጣ አጣዳፊ ተቅማጥ በሽታ።',
   ARRAY['Watery diarrhea','Dehydration'], ARRAY['ውሃማ ተቅማጥ','የውሃ እጥረት'],
   ARRAY['Contaminated water'], ARRAY['የተበከለ ውሃ'],
   ARRAY['Safe water and sanitation'], ARRAY['ንጹህ ውሃና ንፅህና'],
   ARRAY['ORS and antibiotics'], ARRAY['ORS እና አንቲባዮቲክ'],
   'critical', ARRAY['intestines'], ARRAY[]::text[], ARRAY[]::text[], '{"region":"Jimma Zone","prevalence":"medium"}'::jsonb),
  ('dengue-fever', 'Dengue Fever', 'ዴንጊ ትኩሳት', 'infectious', 'Mosquito-borne viral illness causing fever and pain.', 'በትንኝ የሚተላለፍ ቫይረስ በሽታ ነው።',
   ARRAY['Fever','Severe body pain'], ARRAY['ትኩሳት','ከባድ የሰውነት ህመም'],
   ARRAY['Aedes mosquito bites'], ARRAY['የAedes ትንኝ ንክሻ'],
   ARRAY['Mosquito control'], ARRAY['የትንኝ መቆጣጠር'],
   ARRAY['Supportive treatment'], ARRAY['ድጋፍ ሕክምና'],
   'severe', ARRAY['blood'], ARRAY['rainy season'], ARRAY['ዝናባማ ወቅት'], '{"region":"Jimma Zone","prevalence":"low"}'::jsonb)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO medicines (
  slug, name, name_am, category, description, description_am,
  uses, uses_am, dosage, dosage_am, side_effects,
  contraindications, contraindications_am, safety_warnings, safety_warnings_am,
  requires_prescription, ministry_approved, scientific_evidence,
  preparation, preparation_am, indications, indications_am,
  medication_interactions, cultural_context, cultural_context_am
)
VALUES
  ('ginger', 'Ginger', 'ዝንጅብል', 'traditional', 'Traditional remedy for nausea and indigestion.', 'ለማቅለሽለሽና ለሆድ ችግር ባህላዊ መድሀኒት ነው።',
   ARRAY['Nausea'], ARRAY['ማቅለሽለሽ'], '1 cup tea twice daily', 'በቀን 2 ጊዜ 1 ኩባያ ሻይ',
   ARRAY['Heartburn'], ARRAY['Gallstones'], ARRAY['የሐሞት ጠጠር'], ARRAY['Use cautiously in pregnancy'], ARRAY['በእርግዝና ጥንቃቄ'],
   false, true, 'moderate', 'Boil fresh slices in water', 'ትኩስ ቁርጥራጮችን በውሃ ቀቅል',
   ARRAY['Nausea','Indigestion'], ARRAY['ማቅለሽለሽ','የሆድ ችግር'], ARRAY[]::text[], 'Common Ethiopian household remedy.', 'በቤት ውስጥ የተለመደ መድሀኒት።'),
  ('garlic', 'Garlic', 'ነጭ ሽንኩርት', 'traditional', 'Traditional immune-support herb.', 'የኢሚዩን ድጋፍ የሚያደርግ ባህላዊ እፅዋት።',
   ARRAY['Immune support'], ARRAY['የኢሚዩን ድጋፍ'], '1 clove daily', 'በቀን 1 ቁራጭ',
   ARRAY['Bad breath'], ARRAY['Bleeding disorders'], ARRAY['የደም መፍሰስ ችግር'], ARRAY['Avoid before surgery'], ARRAY['ከቀዶ ጥገና በፊት አቁም'],
   false, true, 'moderate', 'Use in food or raw', 'በምግብ ውስጥ ወይም ጥሬ ይጠቀሙ',
   ARRAY['Common cold'], ARRAY['ጉንፋን'], ARRAY[]::text[], 'Used in Ethiopian cooking and traditional care.', 'በኢትዮጵያ ምግብና ባህላዊ እንክብካቤ ውስጥ ይጠቀማል።'),
  ('moringa', 'Moringa', 'ሞሪንጋ', 'traditional', 'Nutrient-rich traditional supplement.', 'በንጥረ ነገር የበለፀገ ባህላዊ ማሟያ ነው።',
   ARRAY['Nutrition support'], ARRAY['የአመጋገብ ድጋፍ'], '1 teaspoon powder daily', 'በቀን 1 የሻይ ማንኪያ ዱቄት',
   ARRAY['Mild GI upset'], ARRAY['Pregnancy caution'], ARRAY['በእርግዝና ጥንቃቄ'], ARRAY['Use verified sources'], ARRAY['የተረጋገጠ ምንጭ ብቻ'],
   false, true, 'moderate', 'Dry leaves and grind powder', 'ቅጠል አድርቀህ ዱቄት አድርግ',
   ARRAY['Nutritional deficiency'], ARRAY['የአመጋገብ እጥረት'], ARRAY[]::text[], 'Promoted in local nutrition programs.', 'በአካባቢ አመጋገብ ፕሮግራሞች ውስጥ ይበረታታል።'),
  ('paracetamol', 'Paracetamol', 'ፓራሲታሞል', 'modern', 'Pain and fever reducer.', 'ህመምና ትኩሳት የሚቀንስ መድሀኒት ነው።',
   ARRAY['Pain','Fever'], ARRAY['ህመም','ትኩሳት'], '500mg every 6 hours', 'በየ6 ሰዓት 500mg',
   ARRAY['Liver toxicity in overdose'], ARRAY['Severe liver disease'], ARRAY['ከባድ የጉበት በሽታ'], ARRAY['Do not exceed daily limit'], ARRAY['ዕለታዊ መጠን አይበልጡ'],
   false, true, 'strong', 'Oral tablet', 'በአፍ የሚወሰድ ክኒን',
   ARRAY['Headache','Fever'], ARRAY['ራስ ምታት','ትኩሳት'], ARRAY[]::text[], 'Widely available OTC medicine.', 'በሰፊው የሚገኝ OTC መድሀኒት።'),
  ('ibuprofen', 'Ibuprofen', 'ኢቡፕሮፌን', 'modern', 'NSAID for pain and inflammation.', 'ለህመምና እብጠት የሚያገለግል NSAID መድሀኒት ነው።',
   ARRAY['Pain','Inflammation'], ARRAY['ህመም','እብጠት'], '200-400mg every 8 hours', 'በየ8 ሰዓት 200-400mg',
   ARRAY['Gastric irritation'], ARRAY['Ulcer disease'], ARRAY['የሆድ ቁስለት'], ARRAY['Take with food'], ARRAY['ከምግብ ጋር ውሰድ'],
   false, true, 'strong', 'Oral tablet', 'በአፍ የሚወሰድ ክኒን',
   ARRAY['Joint pain'], ARRAY['የመገጣጠሚያ ህመም'], ARRAY[]::text[], 'Common anti-inflammatory medicine.', 'የተለመደ ፀረ-እብጠት መድሀኒት።'),
  ('ors', 'ORS', 'ኦአርኤስ', 'modern', 'Oral rehydration salts for dehydration.', 'ለውሃ እጥረት የሚሰጥ የአፍ ፈሳሽ ጨው ነው።',
   ARRAY['Rehydration'], ARRAY['ፈሳሽ መተካት'], 'As directed', 'እንደ መመሪያው',
   ARRAY[]::text[], ARRAY['Severe dehydration requires IV'], ARRAY['ከባድ የውሃ እጥረት IV ይፈልጋል'], ARRAY['Use clean water'], ARRAY['ንጹህ ውሃ ብቻ'],
   false, true, 'strong', 'Dissolve packet in clean water', 'ፓኬት በንጹህ ውሃ ውስጥ ቀላቅል',
   ARRAY['Diarrhea','Vomiting'], ARRAY['ተቅማጥ','ማስታወክ'], ARRAY[]::text[], 'WHO-recommended dehydration support.', 'የWHO የውሃ እጥረት ድጋፍ መንገድ።'),
  ('cetirizine', 'Cetirizine', 'ሴቲሪዚን', 'modern', 'Antihistamine for allergies.', 'ለአለርጂ የሚሰጥ ፀረ-ሂስታሚን መድሀኒት ነው።',
   ARRAY['Allergy relief'], ARRAY['የአለርጂ ማስታገሻ'], '10mg daily', 'በቀን 10mg',
   ARRAY['Drowsiness'], ARRAY['Severe kidney disease'], ARRAY['ከባድ የኩላሊት በሽታ'], ARRAY['Avoid alcohol'], ARRAY['አልኮል አስወግድ'],
   false, true, 'strong', 'Oral tablet', 'በአፍ የሚወሰድ ክኒን',
   ARRAY['Allergic rhinitis'], ARRAY['አለርጂክ ራይኒተስ'], ARRAY[]::text[], 'Common OTC antihistamine.', 'የተለመደ OTC ፀረ-ሂስታሚን መድሀኒት።'),
  ('amoxicillin', 'Amoxicillin', 'አሞክሲሲሊን', 'modern', 'Broad-spectrum antibiotic.', 'ሰፊ ስፔክትረም ያለው አንቲባዮቲክ ነው።',
   ARRAY['Bacterial infections'], ARRAY['ባክቴሪያ ኢንፌክሽን'], '500mg every 8 hours', 'በየ8 ሰዓት 500mg',
   ARRAY['Diarrhea','Rash'], ARRAY['Penicillin allergy'], ARRAY['የፔኒሲሊን አለርጂ'], ARRAY['Complete full course'], ARRAY['ሙሉ ኮርስ አትቁም'],
   true, true, 'strong', 'Oral capsule/suspension', 'በአፍ የሚወሰድ ካፕሱል/ሲረፕ',
   ARRAY['Respiratory infections'], ARRAY['የመተንፈሻ ኢንፌክሽን'], ARRAY[]::text[], 'Prescription antibiotic in Ethiopia.', 'በኢትዮጵያ በሐኪም ትእዛዝ የሚሰጥ አንቲባዮቲክ።'),
  ('metformin', 'Metformin', 'ሜትፎርሚን', 'modern', 'First-line medication for type 2 diabetes.', 'ለዓይነት 2 ስኳር በሽታ የመጀመሪያ መድሀኒት ነው።',
   ARRAY['Blood sugar control'], ARRAY['የደም ስኳር መቆጣጠር'], '500mg once or twice daily', 'በቀን 1-2 ጊዜ 500mg',
   ARRAY['GI upset'], ARRAY['Severe kidney disease'], ARRAY['ከባድ የኩላሊት በሽታ'], ARRAY['Take with meals'], ARRAY['ከምግብ ጋር ውሰድ'],
   true, true, 'strong', 'Oral tablet', 'በአፍ የሚወሰድ ክኒን',
   ARRAY['Type 2 diabetes'], ARRAY['ዓይነት 2 ስኳር በሽታ'], ARRAY[]::text[], 'Common diabetes medication.', 'የተለመደ የስኳር መድሀኒት።'),
  ('amlodipine', 'Amlodipine', 'አምሎዲፒን', 'modern', 'Antihypertensive calcium channel blocker.', 'የደም ግፊት መቀነሻ መድሀኒት ነው።',
   ARRAY['Blood pressure control'], ARRAY['የደም ግፊት መቆጣጠር'], '5-10mg daily', 'በቀን 5-10mg',
   ARRAY['Ankle swelling'], ARRAY['Severe hypotension'], ARRAY['ከባድ ዝቅተኛ የደም ግፊት'], ARRAY['Monitor BP regularly'], ARRAY['የደም ግፊት ይከታተሉ'],
   true, true, 'strong', 'Oral tablet', 'በአፍ የሚወሰድ ክኒን',
   ARRAY['Hypertension'], ARRAY['የደም ግፊት'], ARRAY[]::text[], 'Widely used BP medicine.', 'በሰፊው የሚጠቀሙት የBP መድሀኒት።'),
  ('omeprazole', 'Omeprazole', 'ኦሜፕራዞል', 'modern', 'Proton pump inhibitor for acid disorders.', 'ለሆድ አሲድ ችግሮች የሚሰጥ መድሀኒት ነው።',
   ARRAY['Acid reflux'], ARRAY['የሆድ አሲድ መመለስ'], '20mg daily before food', 'በቀን 20mg ከምግብ በፊት',
   ARRAY['Headache'], ARRAY[]::text[], ARRAY[]::text[], ARRAY['Use shortest effective duration'], ARRAY['በአጭር ጊዜ እንዲቻል'],
   false, true, 'strong', 'Oral capsule', 'በአፍ የሚወሰድ ካፕሱል',
   ARRAY['GERD','Gastritis'], ARRAY['GERD','ጋስትራይቲስ'], ARRAY[]::text[], 'Common acid-control medicine.', 'የተለመደ የአሲድ መቆጣጠሪያ መድሀኒት።'),
  ('salbutamol', 'Salbutamol', 'ሳልቡታሞል', 'modern', 'Bronchodilator inhaler for asthma symptoms.', 'ለአስም ምልክቶች የሚሰጥ የመተንፈሻ መድሀኒት ነው።',
   ARRAY['Bronchodilation'], ARRAY['መተንፈሻ መክፈቻ'], '1-2 puffs as needed', 'እንደ አስፈላጊ 1-2 ፓፍ',
   ARRAY['Tremor','Palpitations'], ARRAY[]::text[], ARRAY[]::text[], ARRAY['Do not overuse rescue inhaler'], ARRAY['የአደጋ ኢንሄለር አብዛኛውን አትጠቀም'],
   false, true, 'strong', 'Metered-dose inhaler', 'ኢንሄለር',
   ARRAY['Asthma symptoms'], ARRAY['የአስም ምልክቶች'], ARRAY[]::text[], 'Essential asthma medicine.', 'ዋና የአስም መድሀኒት ነው።'),
  ('zinc-sulfate', 'Zinc Sulfate', 'ዚንክ ሰልፌት', 'modern', 'Supplement used with ORS in childhood diarrhea.', 'በህፃናት ተቅማጥ ጊዜ ከORS ጋር የሚሰጥ ማሟያ ነው።',
   ARRAY['Diarrhea support'], ARRAY['የተቅማጥ ድጋፍ'], '10-20mg daily (age-based)', 'እድሜ መሰረት 10-20mg በቀን',
   ARRAY['Nausea'], ARRAY[]::text[], ARRAY[]::text[], ARRAY['Give with food if nausea'], ARRAY['ማቅለሽለሽ ካለ ከምግብ ጋር'],
   false, true, 'strong', 'Oral tablet/syrup', 'በአፍ የሚወሰድ ክኒን/ሲረፕ',
   ARRAY['Acute diarrhea'], ARRAY['አጣዳፊ ተቅማጥ'], ARRAY[]::text[], 'Used in child health programs.', 'በህፃናት ጤና ፕሮግራሞች ውስጥ ይጠቀማል።'),
  ('folic-acid', 'Folic Acid', 'ፎሊክ አሲድ', 'modern', 'Vitamin supplement used in pregnancy and anemia prevention.', 'በእርግዝናና የደም ማነስ መከላከል የሚሰጥ ቫይታሚን ማሟያ ነው።',
   ARRAY['Pregnancy support'], ARRAY['የእርግዝና ድጋፍ'], '400mcg daily', 'በቀን 400mcg',
   ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[],
   false, true, 'strong', 'Oral tablet', 'በአፍ የሚወሰድ ክኒን',
   ARRAY['Pregnancy','Anemia prevention'], ARRAY['እርግዝና','የደም ማነስ መከላከል'], ARRAY[]::text[], 'Routine maternal care supplement.', 'በመደበኛ የእናቶች እንክብካቤ ይሰጣል።'),
  ('ferrous-sulfate', 'Ferrous Sulfate', 'ፈረስ ሰልፌት', 'modern', 'Iron supplement for iron deficiency anemia.', 'ለብረት እጥረት የደም ማነስ የሚሰጥ ማሟያ ነው።',
   ARRAY['Iron replacement'], ARRAY['የብረት መተካት'], 'As prescribed', 'እንደ ሐኪም ትእዛዝ',
   ARRAY['Constipation'], ARRAY[]::text[], ARRAY[]::text[], ARRAY['Keep away from children'], ARRAY['ከህፃናት ያርቁ'],
   false, true, 'strong', 'Oral tablet/syrup', 'በአፍ የሚወሰድ ክኒን/ሲረፕ',
   ARRAY['Iron deficiency anemia'], ARRAY['የብረት እጥረት የደም ማነስ'], ARRAY[]::text[], 'Common anemia treatment in primary care.', 'በመጀመሪያ ደረጃ ሕክምና የተለመደ የደም ማነስ ሕክምና።'),
  ('azithromycin', 'Azithromycin', 'አዚትሮማይሲን', 'modern', 'Macrolide antibiotic for selected bacterial infections.', 'ለአንዳንድ ባክቴሪያ ኢንፌክሽን የሚሰጥ አንቲባዮቲክ ነው።',
   ARRAY['Bacterial infections'], ARRAY['ባክቴሪያ ኢንፌክሽን'], 'As prescribed', 'እንደ ሐኪም ትእዛዝ',
   ARRAY['Nausea'], ARRAY[]::text[], ARRAY[]::text[], ARRAY['Use only when indicated'], ARRAY['አስፈላጊ ሲሆን ብቻ ይጠቀሙ'],
   true, true, 'strong', 'Oral tablet/suspension', 'በአፍ የሚወሰድ ክኒን/ሲረፕ',
   ARRAY['Respiratory infections'], ARRAY['የመተንፈሻ ኢንፌክሽን'], ARRAY[]::text[], 'Prescription-only antibiotic.', 'በሐኪም ትእዛዝ ብቻ የሚሰጥ አንቲባዮቲክ።'),
  ('doxycycline', 'Doxycycline', 'ዶክሲሳይክሊን', 'modern', 'Tetracycline antibiotic used for various infections.', 'ለተለያዩ ኢንፌክሽኖች የሚሰጥ ቴትራሳይክሊን አንቲባዮቲክ ነው።',
   ARRAY['Bacterial infections'], ARRAY['ባክቴሪያ ኢንፌክሽን'], 'As prescribed', 'እንደ ሐኪም ትእዛዝ',
   ARRAY['Photosensitivity'], ARRAY['Pregnancy','Children <8'], ARRAY['እርግዝና','ከ8 ዓመት በታች ህፃናት'], ARRAY['Avoid direct sun'], ARRAY['ፀሐይን ያስወግዱ'],
   true, true, 'strong', 'Oral capsule', 'በአፍ የሚወሰድ ካፕሱል',
   ARRAY['Bacterial infections'], ARRAY['ባክቴሪያ ኢንፌክሽን'], ARRAY[]::text[], 'Used under prescription.', 'በሐኪም ትእዛዝ ይሰጣል።'),
  ('clotrimazole', 'Clotrimazole', 'ክሎትሪማዞል', 'modern', 'Antifungal treatment for skin fungal infections.', 'ለቆዳ ፈንገስ ኢንፌክሽን የሚሰጥ ፀረ-ፈንገስ መድሀኒት ነው።',
   ARRAY['Fungal skin infection'], ARRAY['የቆዳ ፈንገስ ኢንፌክሽን'], 'Apply twice daily', 'በቀን 2 ጊዜ ቀባ',
   ARRAY['Local irritation'], ARRAY[]::text[], ARRAY[]::text[], ARRAY['Keep area clean and dry'], ARRAY['ቦታውን ንጹህና ደረቅ አድርግ'],
   false, true, 'strong', 'Topical cream', 'በቆዳ ላይ የሚቀባ ክሬም',
   ARRAY['Ringworm','Athlete foot'], ARRAY['ሪንግዎርም','የእግር ፈንገስ'], ARRAY[]::text[], 'Common antifungal cream.', 'የተለመደ ፀረ-ፈንገስ ክሬም ነው።'),
  ('diclofenac', 'Diclofenac', 'ዲክሎፍናክ', 'modern', 'NSAID for pain and inflammation management.', 'ለህመምና እብጠት የሚሰጥ NSAID መድሀኒት ነው።',
   ARRAY['Pain relief'], ARRAY['ህመም ማስታገሻ'], 'As prescribed', 'እንደ ሐኪም ትእዛዝ',
   ARRAY['GI upset'], ARRAY['Ulcer disease'], ARRAY['የሆድ ቁስለት'], ARRAY['Use lowest effective dose'], ARRAY['በአነስተኛ ውጤታማ መጠን ይጠቀሙ'],
   true, true, 'strong', 'Tablet or topical gel', 'ክኒን ወይም በቆዳ ላይ ጄል',
   ARRAY['Musculoskeletal pain'], ARRAY['የጡንቻ/አጥንት ህመም'], ARRAY[]::text[], 'Used for inflammatory pain.', 'ለእብጠት ህመም ይሰጣል።')
ON CONFLICT (slug) DO NOTHING;
